<a href="https://colab.research.google.com/github/Schiavi13/analisis-impacto-covid19-en-inversion-ecoeficiencia-empresarial-2019-2023/blob/luis_001/src/merge_datasets_ambiental_general_2019.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Unificación de datasets ambiental y general del año 2019

In [ ]:
# importar librerias
import pandas as pd
print("Carga de librerías exitosa")

Carga de librerías exitosa

In [ ]:
# Carga datasets ambiental y general
df_ambiental_2019 = pd.read_csv("/content/drive/MyDrive/Bootcamp Análisis de Datos/Grupo Q/data/procesados/ambiental/2019_eas_ambiental.csv")
df_ambiental_2019.head()

,id_empresa,periodo,id_sector,sector_desc,gastos_totales,gasto_gestion_amb,contrata_personal_amb,realiza_inv_red_emision_aire,realiza_inv_ahorro_agua,realiza_inv_inst_med_agua,...,realiza_otras_inv_amb,realiza_gasto_red_emision_aire,realiza_gasto_ahorro_agua,realiza_gasto_inst_med_agua,realiza_gasto_disp_desechos,realiza_gasto_protec_suelo,realiza_gasto_evita_ruido_vibra,realiza_gasto_terceros_amb,realiza_gasto_energia_limp,realiza_otros_gastos_amb
0,10001,2019,I1,alojamiento,2287702,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,10002,2019,I1,alojamiento,5020785,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,10003,2019,I1,alojamiento,15309856,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,10004,2019,I1,alojamiento,8978494,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,10005,2019,I2,expendio de alimentos,29103165,227327,1,0,0,0,...,0,1,1,0,0,0,0,1,0,0

In [ ]:
df_general_2019 = pd.read_csv("/content/drive/MyDrive/Bootcamp Análisis de Datos/Grupo Q/data/procesados/general/2019_eas_general.csv")
df_general_2019.head()

,id_empresa,anio_inicio,periodo,id_sector_general,total_ingresos,personal_remunerado,gasto_remuneracion_personal,gasto_personal_total,personal_mujeres,personal_hombres,personal_ocupado,imp_ind_com,imp_renta_equidad,imp_otros,gasto_servicios_publicos,gasto_energia_electrica,gasto_gas_natural
0,10001,1992,2019,I1,2690535.0,42.0,806770.0,875670.0,26.0,16.0,42.0,31545.0,0.0,14564.0,57579.0,244691.0,104802.0
1,10002,1994,2019,I1,5198956.0,74.0,1490082.0,1498992.0,39.0,36.0,75.0,3906.0,0.0,102267.0,170977.0,425162.0,61113.0
2,10003,1999,2019,I1,14153289.0,75.0,2199361.0,2365296.0,72.0,120.0,192.0,168172.0,0.0,102069.0,201072.0,1410618.0,263741.0
3,10004,2009,2019,I1,10684133.0,39.0,695317.0,695317.0,24.0,15.0,39.0,88735.0,0.0,0.0,345980.0,456870.0,0.0
4,10005,1957,2019,I2,26319862.0,50.0,2498261.0,2886717.0,81.0,146.0,227.0,146999.0,0.0,358035.0,394582.0,1251610.0,121518.0

Se unifican los datasets mediante un inner join con el id de la empresa

In [ ]:
# Merge de los dos datasets por campo id_empresa
df_servicios_unificado_2019 = pd.merge(df_ambiental_2019, df_general_2019, on="id_empresa", how="inner")
df_servicios_unificado_2019.head()

,id_empresa,periodo_x,id_sector,sector_desc,gastos_totales,gasto_gestion_amb,contrata_personal_amb,realiza_inv_red_emision_aire,realiza_inv_ahorro_agua,realiza_inv_inst_med_agua,...,gasto_personal_total,personal_mujeres,personal_hombres,personal_ocupado,imp_ind_com,imp_renta_equidad,imp_otros,gasto_servicios_publicos,gasto_energia_electrica,gasto_gas_natural
0,10001,2019,I1,alojamiento,2287702,0,1,0,0,0,...,875670.0,26.0,16.0,42.0,31545.0,0.0,14564.0,57579.0,244691.0,104802.0
1,10002,2019,I1,alojamiento,5020785,0,0,0,0,0,...,1498992.0,39.0,36.0,75.0,3906.0,0.0,102267.0,170977.0,425162.0,61113.0
2,10003,2019,I1,alojamiento,15309856,0,0,0,0,0,...,2365296.0,72.0,120.0,192.0,168172.0,0.0,102069.0,201072.0,1410618.0,263741.0
3,10004,2019,I1,alojamiento,8978494,0,1,0,0,0,...,695317.0,24.0,15.0,39.0,88735.0,0.0,0.0,345980.0,456870.0,0.0
4,10005,2019,I2,expendio de alimentos,29103165,227327,1,0,0,0,...,2886717.0,81.0,146.0,227.0,146999.0,0.0,358035.0,394582.0,1251610.0,121518.0

In [ ]:
# inspecciona el dataframe unificado
df_servicios_unificado_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5935 entries, 0 to 5934
Data columns (total 40 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id_empresa                       5935 non-null   int64
 1   periodo_x                        5935 non-null   int64
 2   id_sector                        5935 non-null   object
 3   sector_desc                      5935 non-null   object
 4   gastos_totales                   5935 non-null   int64
 5   gasto_gestion_amb                5935 non-null   int64
 6   contrata_personal_amb            5935 non-null   int64
 7   realiza_inv_red_emision_aire     5935 non-null   int64
 8   realiza_inv_ahorro_agua          5935 non-null   int64
 9   realiza_inv_inst_med_agua        5935 non-null   int64
 10  realiza_inv_disp_desechos        5935 non-null   int64
 11  realiza_inv_protec_suelo         5935 non-null   int64
 12  realiza_inv_evita_ruido_vibra    5935 non-null   int64
 13  realiza_inv_energia_limp         5935 non-null   int64
 14  realiza_otras_inv_amb            5935 non-null   int64
 15  realiza_gasto_red_emision_aire   5935 non-null   int64
 16  realiza_gasto_ahorro_agua        5935 non-null   int64
 17  realiza_gasto_inst_med_agua      5935 non-null   int64
 18  realiza_gasto_disp_desechos      5935 non-null   int64
 19  realiza_gasto_protec_suelo       5935 non-null   int64
 20  realiza_gasto_evita_ruido_vibra  5935 non-null   int64
 21  realiza_gasto_terceros_amb       5935 non-null   int64
 22  realiza_gasto_energia_limp       5935 non-null   int64
 23  realiza_otros_gastos_amb         5935 non-null   int64
 24  anio_inicio                      5935 non-null   int64
 25  periodo_y                        5935 non-null   int64
 26  id_sector_general                5935 non-null   object
 27  total_ingresos                   5935 non-null   float64
 28  personal_remunerado              5935 non-null   float64
 29  gasto_remuneracion_personal      5935 non-null   float64
 30  gasto_personal_total             5935 non-null   float64
 31  personal_mujeres                 5935 non-null   float64
 32  personal_hombres                 5935 non-null   float64
 33  personal_ocupado                 5935 non-null   float64
 34  imp_ind_com                      5935 non-null   float64
 35  imp_renta_equidad                5935 non-null   float64
 36  imp_otros                        5935 non-null   float64
 37  gasto_servicios_publicos         5935 non-null   float64
 38  gasto_energia_electrica          5935 non-null   float64
 39  gasto_gas_natural                5935 non-null   float64
dtypes: float64(13), int64(24), object(3)
memory usage: 1.8+ MB

## Modificación de tipos de datos

Se ajustan los tipos de datos de las columnas

In [ ]:
df_servicios_unificado_2019 = df_servicios_unificado_2019.astype(
    {
        'gastos_totales': 'float64',
        'gasto_gestion_amb': 'float64',
        'total_ingresos': 'float64',
        'personal_remunerado': 'int64',
        'gasto_remuneracion_personal': 'float64',
        'gasto_personal_total': 'float64',
        'personal_mujeres': 'int64',
        'personal_hombres': 'int64',
        'personal_ocupado': 'int64',
        'imp_ind_com': 'float64',
        'imp_renta_equidad': 'float64',
        'imp_otros': 'float64',
        'gasto_servicios_publicos': 'float64',
        'gasto_energia_electrica': 'float64',
        'gasto_gas_natural': 'float64'
    }
)
df_servicios_unificado_2019.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5935 entries, 0 to 5934
Data columns (total 40 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   id_empresa                       5935 non-null   int64
 1   periodo_x                        5935 non-null   int64
 2   id_sector                        5935 non-null   object
 3   sector_desc                      5935 non-null   object
 4   gastos_totales                   5935 non-null   float64
 5   gasto_gestion_amb                5935 non-null   float64
 6   contrata_personal_amb            5935 non-null   int64
 7   realiza_inv_red_emision_aire     5935 non-null   int64
 8   realiza_inv_ahorro_agua          5935 non-null   int64
 9   realiza_inv_inst_med_agua        5935 non-null   int64
 10  realiza_inv_disp_desechos        5935 non-null   int64
 11  realiza_inv_protec_suelo         5935 non-null   int64
 12  realiza_inv_evita_ruido_vibra    5935 non-null   int64
 13  realiza_inv_energia_limp         5935 non-null   int64
 14  realiza_otras_inv_amb            5935 non-null   int64
 15  realiza_gasto_red_emision_aire   5935 non-null   int64
 16  realiza_gasto_ahorro_agua        5935 non-null   int64
 17  realiza_gasto_inst_med_agua      5935 non-null   int64
 18  realiza_gasto_disp_desechos      5935 non-null   int64
 19  realiza_gasto_protec_suelo       5935 non-null   int64
 20  realiza_gasto_evita_ruido_vibra  5935 non-null   int64
 21  realiza_gasto_terceros_amb       5935 non-null   int64
 22  realiza_gasto_energia_limp       5935 non-null   int64
 23  realiza_otros_gastos_amb         5935 non-null   int64
 24  anio_inicio                      5935 non-null   int64
 25  periodo_y                        5935 non-null   int64
 26  id_sector_general                5935 non-null   object
 27  total_ingresos                   5935 non-null   float64
 28  personal_remunerado              5935 non-null   int64
 29  gasto_remuneracion_personal      5935 non-null   float64
 30  gasto_personal_total             5935 non-null   float64
 31  personal_mujeres                 5935 non-null   int64
 32  personal_hombres                 5935 non-null   int64
 33  personal_ocupado                 5935 non-null   int64
 34  imp_ind_com                      5935 non-null   float64
 35  imp_renta_equidad                5935 non-null   float64
 36  imp_otros                        5935 non-null   float64
 37  gasto_servicios_publicos         5935 non-null   float64
 38  gasto_energia_electrica          5935 non-null   float64
 39  gasto_gas_natural                5935 non-null   float64
dtypes: float64(11), int64(26), object(3)
memory usage: 1.8+ MB

Existen columnas con el mismo nombre en ambos datasets, por lo tanto pandas les modifica el nombre, a continuación se deja una sola con el nombre original.

In [ ]:
# Elimina columna periodo repetida
df_servicios_unificado_2019.drop(columns=["periodo_y"], inplace=True)
df_servicios_unificado_2019.rename(columns={"periodo_x":"periodo"}, inplace=True)
print(df_servicios_unificado_2019.columns)

Index(['id_empresa', 'periodo', 'id_sector', 'sector_desc', 'gastos_totales',
       'gasto_gestion_amb', 'contrata_personal_amb',
       'realiza_inv_red_emision_aire', 'realiza_inv_ahorro_agua',
       'realiza_inv_inst_med_agua', 'realiza_inv_disp_desechos',
       'realiza_inv_protec_suelo', 'realiza_inv_evita_ruido_vibra',
       'realiza_inv_energia_limp', 'realiza_otras_inv_amb',
       'realiza_gasto_red_emision_aire', 'realiza_gasto_ahorro_agua',
       'realiza_gasto_inst_med_agua', 'realiza_gasto_disp_desechos',
       'realiza_gasto_protec_suelo', 'realiza_gasto_evita_ruido_vibra',
       'realiza_gasto_terceros_amb', 'realiza_gasto_energia_limp',
       'realiza_otros_gastos_amb', 'anio_inicio', 'id_sector_general',
       'total_ingresos', 'personal_remunerado', 'gasto_remuneracion_personal',
       'gasto_personal_total', 'personal_mujeres', 'personal_hombres',
       'personal_ocupado', 'imp_ind_com', 'imp_renta_equidad', 'imp_otros',
       'gasto_servicios_publicos', 'gasto_energia_electrica',
       'gasto_gas_natural'],
      dtype='object')

## Verificación de consistencia de id_empresa e id_sector
Se comparan los id_sector e id_sector_general, y si son inconsistentes se busca la razón para realizar ajustes o eliminar registros.

In [ ]:
# Extrae id_sector diferentes
condicion_diferente_Sector = df_servicios_unificado_2019['id_sector'] != df_servicios_unificado_2019['id_sector_general']
df_servicios_unificado_2019.loc[condicion_diferente_Sector,
                                ['id_empresa',
                                 'id_sector',
                                 'total_ingresos',
                                 'id_sector_general']]

      id_empresa id_sector  total_ingresos id_sector_general
23         10030        LN       3014053.0               LN1
124        10146        LN      61560450.0               LN1
132        10156        LN      52531611.0               LN1
181        10220        LN       8366780.0               LN1
486        10585        LN      10711714.0               LN1
...          ...       ...             ...               ...
5822       19616        LN       8114412.0               LN1
5823       19617        LN       4568203.0               LN1
5890       19690        LN       4138306.0               LN1
5909       19709        LN      11672111.0               LN1
5920       19721        LN      66806813.0               LN1

[312 rows x 4 columns]

Se evidencia que el sector "LN1" en id_sector_general tiene un número extra, se puede ajustar a "LN" para que coincida sin modificar los datos. Por otro lado, existen id_sector que no tienen relación, se aislan y se eliminan del análisis estos registros.

In [ ]:
# Corrige id_sector_general LN1 a LN
df_servicios_unificado_2019['id_sector_general'] = df_servicios_unificado_2019['id_sector_general'].mask(df_servicios_unificado_2019['id_sector_general']=='LN1', 'LN')
condicion_diferente_Sector = df_servicios_unificado_2019['id_sector'] != df_servicios_unificado_2019['id_sector_general']
df_servicios_unificado_2019.loc[condicion_diferente_Sector,
                                ['id_empresa',
                                 'id_sector',
                                 'total_ingresos',
                                 'id_sector_general']]

      id_empresa id_sector  total_ingresos id_sector_general
488        10587        LN       3665724.0                I1
689        10820        M1       5977258.0                LN
1022       11229        H2       4140773.0                H1
1286       11534         S       7536269.0                N3
1664       12023        N5      55728626.0                M2
2169       12735        LN      23332613.0                N4
2207       12787         Q        247264.0                LN
2279       12895        N3      16356007.0                H1
2729       13507        N3       3203711.0                H1
4650       18008        M1      14638274.0                LN

In [ ]:
# Elimina registros con incongruencias en id_sector e id_sector_general
df_servicios_unificado_2019 = df_servicios_unificado_2019[df_servicios_unificado_2019['id_sector'] == df_servicios_unificado_2019['id_sector_general']]
df_servicios_unificado_2019.shape

(5925, 39)

In [ ]:
# Verifica id_sector
condicion_diferente_Sector = df_servicios_unificado_2019['id_sector'] != df_servicios_unificado_2019['id_sector_general']
df_servicios_unificado_2019.loc[condicion_diferente_Sector,
                                ['id_empresa',
                                 'id_sector',
                                 'total_ingresos',
                                 'id_sector_general']]

Empty DataFrame
Columns: [id_empresa, id_sector, total_ingresos, id_sector_general]
Index: []

Se eliminaron satisfactoriamente los registros con id_sector inconsistentes

## Exporta datos
Exporta el dataframe unificado a la carpeta de datasets unificados

In [ ]:
# Exporta el dataframe como csv
df_servicios_unificado_2019.to_csv("/content/drive/MyDrive/Bootcamp Análisis de Datos/Grupo Q/data/procesados/unificados/2019_eas_unificado.csv", index=False)